### PR TITLE
Hacs Community Store support

### PR DESCRIPTION
**Pull request by sebiweise**
Added Hac Community manifest file.

Issues:

- www files are not copied

### CODE REVIEW

**Comment by rgruebel** [comment]
Thank you. I think we have two options to solve the problem:

1. Copy the files on start (async_setup) to www folder
2. Create a Homeassistant View and register it.

As I recently noticed that the www folder is not protected, I would prefer option 2. I can' t find any official documentation on how to do this, so I would have to check other custom components first. (Like HACS for example)

**Comment by ckesc** [comment]
@sebiweise any progress? Really waiting for HACS support :)

**Comment by sebiweise** [comment]
I'm sorry I've been up to my ears a lot lately. I'll take a look at the options and see if I can find a solution. Suggestions gladly :)

**Comment by sebiweise** [comment]
@rgruebel solved it. It is possible to make the whole thing even more beautiful if changes are made to www. That's how it works right now.

**Comment by rgruebel** [comment]
Thank you

**Comment by depen84** [comment]
Hi guys,

I can´t get it to work. I installed it via HACS and added configuration.yaml as described, restarted and ran the service. In the dev-state view I can se that zigbee2mqtt_networkmap.map_last_update has been set.

Now to my issue: When I click the panel I can only see the topic in the top and engine etc. in the bottom. The middle is blank, no network map...

I run Hass.io 94.4 on Ubuntu server 18.04.

**Comment by rgruebel** [comment]
This is a HACS Bug: custom-components/hacs#321 and #17

**Pull request merged**
